// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRa3HHm1uXBgbrzn1Ub3mBOjtb_NhrUUU',
    appId: '1:505647378372:web:96166c1d00e9dfb468be91',
    messagingSenderId: '505647378372',
    projectId: 'mangaale',
    authDomain: 'mangaale.firebaseapp.com',
    storageBucket: 'mangaale.firebasestorage.app',
    measurementId: 'G-N5QP9DK8JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAGrcsBsqk73iD2yc3PAVngaUsP9OuKJg',
    appId: '1:505647378372:android:537862d182d3486268be91',
    messagingSenderId: '505647378372',
    projectId: 'mangaale',
    storageBucket: 'mangaale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCMYzZd30y6rcafjNuZmoz8gDCjeV5M4',
    appId: '1:505647378372:ios:85d6bab46fc2184768be91',
    messagingSenderId: '505647378372',
    projectId: 'mangaale',
    storageBucket: 'mangaale.firebasestorage.app',
    iosBundleId: 'com.turquoise.turquoiseDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCMYzZd30y6rcafjNuZmoz8gDCjeV5M4',
    appId: '1:505647378372:ios:85d6bab46fc2184768be91',
    messagingSenderId: '505647378372',
    projectId: 'mangaale',
    storageBucket: 'mangaale.firebasestorage.app',
    iosBundleId: 'com.turquoise.turquoiseDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRa3HHm1uXBgbrzn1Ub3mBOjtb_NhrUUU',
    appId: '1:505647378372:web:27dcedaae94dd1e268be91',
    messagingSenderId: '505647378372',
    projectId: 'mangaale',
    authDomain: 'mangaale.firebaseapp.com',
    storageBucket: 'mangaale.firebasestorage.app',
    measurementId: 'G-MLP43TGP84',
  );
}
